POST http://localhost:8000/api/users/
content-type: application/json

{
  "username": "Koos",
  "email": "koos@example.com",
  "full_name": "The Admin"
}


###
POST http://localhost:8000/api/users/
content-type: application/json

{
  "username": "Mary",
  "email": "mary@example.com",
  "full_name": "Mary Poppins"
}

### Get all users
GET http://localhost:8000/api/users/


###
POST http://localhost:8000/api/users/18/set_auth
 

###
PUT http://localhost:8000/api/users/17
content-type: application/json

{
  "full_name": "Koos Kombuis"
}


###
DELETE http://localhost:8000/api/users/8


### Get specific user
GET http://localhost:8000/api/users/8


### Get unknown user
GET http://localhost:8000/api/users/99


###
GET http://localhost:8000/api/users/uuid/b51b3124-7395-461a-8a08-840e36a58037


###
GET http://localhost:8000/api/users/username/admin@example.com


######## Test roles

###
POST http://localhost:8000/api/roles/
content-type: application/json

{
  "name": "Document creator",
  "description": "Document creator"
}


### Get all roles
GET http://localhost:8000/api/roles/


###
PUT http://localhost:8000/api/roles/18
Content-Type: application/json

{
  "description": "Creative document writer"
}


###
DELETE http://localhost:8000/api/roles/14



### Get specific role
GET http://localhost:8000/api/roles/18




### Get none exisitant role 
GET http://localhost:8000/api/roles/99



###
GET http://localhost:8000/api/roles/uuid/9984d5d6-9d1b-46c6-adc8-042bd80950eb


###
POST http://localhost:8000/api/users/8/role/18


###
GET http://localhost:8000/api/users/8/roles



###
GET http://localhost:8000/api/roles/12/users


###
POST http://localhost:8000/api/roles/12/user/3

###
POST http://localhost:8000/api/roles/13/user/3

###
GET http://localhost:8000/api/users/3/roles


###
DELETE http://localhost:8000/api/roles/12/user/3

###
DELETE http://localhost:8000/api/users/3/role/12


###
POST http://localhost:8000/api/auth/users/18/set_auth
Content-Type: application/json

{
  "password": "test1234"
}

 
###
POST http://localhost:8000/api/auth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=Mary&password=test1234


###
GET http://localhost:8000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXJ5IiwiZXhwIjoxNzE3NDIwNDE5fQ.e7dHjNkjCICDrcc0rLa5-0ejWDQcy689fqBee1q2c3Q




